load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

filegroup(
    name = "all_files",
    testonly = True,
    srcs = [
        "BUILD.bazel",
        "langs.go",
        "main.go",
        "//v2/cmd/gazelle/profile:all_files",
        "//v2/cmd/gazelle/update:all_files",
    ],
    visibility = ["//visibility:public"],
)

go_library(
    name = "gazelle_lib",
    srcs = [
        "langs.go",
        "main.go",
    ],
    importpath = "github.com/bazel-contrib/bazel-gazelle/v2/cmd/gazelle",
    visibility = ["//visibility:private"],
    deps = [
        "//config",
        "//language",
        "//language/bazel/visibility",
        "//language/go",
        "//language/proto",
        "//resolve",
        "//v2/cmd/gazelle/update",
        "//v2/walk",
    ],
)

go_binary(
    name = "gazelle",
    embed = [":gazelle_lib"],
    visibility = ["//visibility:public"],
)
