/* Copyright 2025 The Bazel Authors. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/token"
	"go/types"
	"os"
	"strings"
	"text/template"

	"golang.org/x/tools/go/gcexportdata"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

const templateSrc = `// Generated by gen_gazelle_binary_main. DO NOT EDIT.

package main

import "github.com/bazel-contrib/bazel-gazelle/v2/compat"

import ({{range .Imports}}
	"{{.}}"{{end}}
)

var languages = []compat.CompleteLanguage{{"{"}}{{range .Calls}}
	{{.}},{{end}}
}
`

var tmpl = template.Must(template.New("gen_gazelle_binary_main").Parse(templateSrc))

func run(args []string) error {
	fs := flag.NewFlagSet("gen_gazelle_binary_main", flag.ContinueOnError)
	var outPath string
	fs.StringVar(&outPath, "o", "", "path to output file")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if outPath == "" {
		return fmt.Errorf("-o not set")
	}

	fset := token.NewFileSet()
	imports := make(map[string]*types.Package)
	var params struct {
		Imports, Calls []string
	}
	for _, arg := range fs.Args() {
		imp, fileName, ok := strings.Cut(arg, "=")
		if !ok {
			return fmt.Errorf("couldn't parse argument %q: expected importpath=filename", arg)
		}
		pkgName, v2, err := isV2(imp, fileName, fset, imports)
		if err != nil {
			return err
		}
		var call string
		if v2 {
			call = fmt.Sprintf(`compat.LanguageWithDefaults(%s.NewLanguageV2())`, pkgName)
		} else {
			call = fmt.Sprintf(`compat.LanguageV2(%s.NewLanguage())`, pkgName)
		}
		params.Imports = append(params.Imports, imp)
		params.Calls = append(params.Calls, call)
	}

	buf := &bytes.Buffer{}
	if err := tmpl.Execute(buf, params); err != nil {
		return err
	}
	return os.WriteFile(outPath, buf.Bytes(), 0666)
}

func isV2(imp, fileName string, fset *token.FileSet, imports map[string]*types.Package) (pkgName string, v2 bool, err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("determining extension version for %s in %s: %w", imp, fileName, err)
		}
	}()

	r, err := os.Open(fileName)
	if err != nil {
		return "", false, err
	}
	defer r.Close()
	xr, err := gcexportdata.NewReader(r)
	if err != nil {
		return "", false, err
	}
	if _, err := gcexportdata.Read(xr, fset, imports, imp); err != nil {
		return "", false, err
	}
	pkg := imports[imp]
	if pkg.Scope().Lookup("NewLanguageV2") != nil {
		return pkg.Name(), true, nil
	} else if pkg.Scope().Lookup("NewLanguage") != nil {
		return pkg.Name(), false, nil
	} else {
		return "", false, fmt.Errorf("package %s does not contain a NewV2 or New function that returns a language extension", imp)
	}
}
