filegroup(
    name = "all_files",
    testonly = True,
    srcs = [
        "BUILD.bazel",
        "//v2/internal/gen_gazelle_binary_main:all_files",
        "//v2/internal/module:all_files",
        "//v2/internal/version:all_files",
        "//v2/internal/wspace:all_files",
    ],
    visibility = ["//visibility:public"],
)
