load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "visibility",
    srcs = [
        "config.go",
        "lang.go",
    ],
    importpath = "github.com/bazel-contrib/bazel-gazelle/v2/language/bazel/visibility",
    visibility = ["//visibility:public"],
    deps = [
        "//v2/config",
        "//v2/language",
        "//v2/merger",
        "//v2/rule",
    ],
)

go_test(
    name = "visibility_test",
    srcs = ["lang_test.go"],
    deps = [
        ":visibility",
        "//v2/config",
        "//v2/language",
        "//v2/rule",
    ],
)

filegroup(
    name = "all_files",
    testonly = True,
    srcs = [
        "BUILD.bazel",
        "config.go",
        "lang.go",
        "lang_test.go",
    ],
    visibility = ["//visibility:public"],
)
